### ISSUE TITLE
conda install

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/snk#20]
Add a conda install option

**Comment by Wytamma** [comment]
Because snk.CLI depends on conda it should probably just be installed though conda

**Comment by pbousquets** [comment]
Hi @Wytamma! Would it be possible to make conda optional? I wanted to create an easy program to run for people with low programming knowledge. It's very easy to simply run `pip install mypackage` to install it, but if the users need conda, they might get into problems to install it. If only using conda was optional, that would circumvent part of the problem.

Very cool program anyway, Snk has made my life much easier! :)

Best,
Pablo

**Comment by Wytamma** [comment]
Good point! Thanks @pbousquets, I think I'll try to make `conda` optional. This issue is just about making a conda install option so that those that use `conda` don't have to use `pip`. But I'll keep pip users in mind.

**Comment by Wytamma** [comment]
Oh and btw `conda` itself is optional at the moment, i.e. you can install and run a pipeline as long as it doesn't use a conda env in a rule. For example:

```bash
pip instal snk
```

```bash
echo "print('hello')" > Snakefile
```

```bash
snk install -n example . 
```

```bash
$ example run 
hello
```

**Comment by pbousquets** [comment]
Oh, I ran into conda-related issues and thought conda was mandatory, specially when I found this issue. I'll investigate a bit more (I have no conda dependencies in my pipeline), and I'll create an issue in case I can't solve it myself. 

Thank you very much for your quick response!
