### ISSUE TITLE
Snakemake version 8

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/snk#53]
Snakemake version 8 is now out and has a lot of changes. Need to update snk to work with this new version.

**Comment by mrvollger** [comment]
I'm commenting so I get pinged when this gets addressed. Excited to try in the future!

**Comment by Wytamma** [comment]
Solved in #68 @mrvollger (snk-cli [v0.2.0](https://github.com/Wytamma/snk-cli/releases/tag/v0.2.0))
