### ISSUE TITLE
Cluster flag for snk

### ISSUE THREAD

**Issue by Kobie-Kirven** [Wytamma/snk#65]
Hi @Wytamma, I have really enjoyed using snk! I was wondering if there is a way to specify the '--cluster' flag for Snakemake from the snk command line? 

Best,
Kobie.

**Comment by Wytamma** [comment]
Hi @Kobie-Kirven! 

You should be able to pass any additional snakemake cli to the Snk cli and they will be forwarded to snakemake e.g. `workflow run --cluster qsub` will run `snakemake --cluster qsub …` internally. If the snakemake flag clashes with your workflow cli I.e you have `cluster: …` in your config then you can prepend `--snake` to any flags you want to ensure get passed to snakemake e.g. `workflow run --snake--cluster qsub`.

let me know if you have any other issues. Glad that you’re enjoying snk :)

**Comment by Kobie-Kirven** [comment]
Hi @Wytamma, thank you for your reply! That's good to know about the flag forwarding and I got it working now. Thanks again!

Best,
Kobie.
