### ISSUE TITLE
Gitpython - Snk-cli conflicts while writing pyproject

### ISSUE THREAD

**Issue by Andyargueasae** [Wytamma/snk#74]
Hello Wytamma,

I am Andy, Rob supervises my PhD. I am currently working on a snakemake workflow "ChloroScan" that incorporates snk-cli. But recently I found that my GitPython version is too early that my git hub repo triggers warnings, and asks me to upgrade gitpython to 3.1.43 (>= 3.1.32) to resolve these security warnings. I tried to upgrade gitpython in pyproject.toml for my repository, but found that by having snk >= 0.24.1 and snk-cli >= 0.1.2, the gitpython version is required to be <= 3.1.31, making it impossible to finish this upgrade. 

I hereby wonder if there are any solutions.

Cheers
Andy

**Comment by Wytamma** [comment]
Thanks Andy! 

Just summarising the solution: When building a standalone cli with snk-cli you don't need to depend on snk only snk-cli so you can drop snk from the pyproject.toml file and that fixes the dependency issue. 

-W
