### ISSUE TITLE
snk does not work with the tag command

### ISSUE THREAD

**Issue by cmeesters** [Wytamma/snk#80]
Hi,

pretty interesting tool! I was asked to review, probably will not find the time to do so, but will start playing around a bit and wonder, whether this tool will become mature enough to be incorporated into the snakemake repo trunk and become a viable alternative to snakedeploy.

Well, I tried to install a workflow, which is still in development. It is registered witht the catalog, but not listed as a "Standardized workflow", yet.

The command I tried with the snk response, was:

```shell
$ snk install snakemake-workflows/transcriptome-differential-expression  --snakemake 8.24.1 -d snakemake-executor-plugin-slurm -t 1.4.1
Could not find workflow: transcriptome-differential-expression
```
It works without specifiying the tag, though. So, in some sense the error message is misleading. The release in question does exist, perhaps you can dig into this issue and refine the error message?

**Comment by Wytamma** [comment]
Thanks @cmeesters!

It's because the tag must match exactly i.e. `v1.4.1` not `1.4.1. But the error message is misleading so I'll update so it says "tag not found".

Being incorporated into snakemake would be the dream :D

**Comment by cmeesters** [comment]
ah, stupid me - then perhaps it might be a good idea and test for `v` and prepend it, if missing? I guess this might be a common mistake, if your tool receives wider recognition.

**Comment by Wytamma** [comment]
No worries, Easy mistake to make. I've update the error message. Can't prepend the `v` because you could have tags that don't follow major.minor.release formatting. Thanks for the issue!
