### ISSUE TITLE
JOSS review: Should @ktmeaton be included in the author list?

### ISSUE THREAD

**Issue by huddlej** [Wytamma/snk#83]
When reviewing the JOSS review checklist item about authorship, I noticed that @ktmeaton has a [nonzero code/doc contribution to snk](https://github.com/Wytamma/snk/graphs/contributors) but isn't in the author list. Should they be included since another person who does not appear to have code/manuscript contributions is listed as a co-author?

Related to https://github.com/openjournals/joss-reviews/issues/7410

**Comment by Wytamma** [comment]
Probably! @ktmeaton want to be a coauthor?

The other author was a major contributor of the [McCoy](https://github.com/mccoy-devs/mccoy/graphs/contributors) project in which Snk was initially conceived and developed.

**Comment by ktmeaton** [comment]
Congratulations on your paper submission @Wytamma, `snk` is an awesome tool! I don't think my very small pull request warrants co-author status but thank you for asking 😊 (I actually didn't remember what my code contribution was until I dug through git. Which I think is additional evidence that I haven't made a substantial contribution.)

**Comment by Wytamma** [comment]
Thanks @ktmeaton! I'll make sure I update the paper to include an acknowledgement of your contribution. You are a fantastic open-source community member :)
