### ISSUE TITLE
JOSS Review: snk.yaml schema versions

### ISSUE THREAD

**Issue by beardymcjohnface** [Wytamma/snk#92]
https://github.com/openjournals/joss-reviews/issues/7410

The snk.yaml expects certain fields etc when building the CLI. The schema might change over time. Would it be sensible to add a schema version to the snk.yaml to ensure backwards compatibility for newer versions of snk with older pipelines using the earlier schemas? Something like:

```yaml
# snk.yaml
schema: 1.0
logo: yeet
...
```

**Comment by Wytamma** [comment]
Thanks again @beardymcjohnface! 

I've been thinking about this one... As the scheme is tied to the `snk-cli` version and independent of `snk` it acts as a sort of schema versioning i.e. you can specify the `snk-cli` version at install time to install older pipelines or . 

E.g. this will install mapache ensuring the `snk-cli` version (schema) is >= 0.6.1.

```bash
snk install https://github.com/sneuensc/mapache -d "snk_cli>=0.6.1" 
```

There may be a cleaner way to do this i.e. the same way I check for min snakemake version so I'll leave this issue open for now.

**Comment by Wytamma** [comment]
I ended up just adding `min_snk_cli_version` to the SnkConfig class so you can set this in the `snk.yaml` file and snk will make sure it uses `snk_cli>=min_snk_cli_version`.
